### ISSUE TITLE
MTB won't work with macOS 12.6 (and 11.7)

### ISSUE THREAD

**Issue by berkue** [apparition47/MailTrackerBlocker#186]
UUID is the same as in 12.5: A4B49485-0377-4FAB-8D8E-E3B8018CFC21

AppleMail is now Version 16.0 (3696.120.41.1.1) in macOS 12.6

Please fix this.

Thank You!

**Comment by MarkSealey** [comment]
Same here. No longer works. Thanks in advance for e fix!

**Comment by edmechem** [comment]
Worked in macOS 11.6.(whateverMinorVersionItWas) Big Sur; doesn't work now in macOS 11.7 Big Sur.
Mail.app has same UUID: `D985F0E4-3BBC-4B95-BBA1-12056AC4A531` as it did previously.

I edited MailTrackerBlocker's Info.plist to add a new section:
`<key>Supported11.7PluginCompatibilityUUIDs</key>`
`<array>`
`<string>D985F0E4-3BBC-4B95-BBA1-12056AC4A531</string>`
`</array>`
just underneath the existing one for 11.6.

I followed the instructions here https://c-command.com/spamsieve/help/resetting-mail-s-privat to successfully delete Mail's Private Plug-Ins Folder; I didn't need to do the whole restart with SIP off procedure, it deleted right away.

Still doesn't work.

**Comment by apparition47** [comment]
@edmechem Thanks for the 11.7 UUID confirmation. Feel free to open a PR next time that happens. Unfortunately, you can't change the Info.plist in your local mailbundle due to signing.

@berkue Thanks for the 12.6 UUID.

Should be all fixed in 0.7.4.

**Comment by MarkSealey** [comment]
I'm still getting the error with [this file](https://github.com/apparition47/MailTrackerBlocker/releases/download/0.7.4/MailTrackerBlocker.pkg
).
